name: unconstrained

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Test Container
        run: docker build --target=test --tag=test .
        
      - name: Run Tests
        run: docker run test pytest
      